pipeline{
    environment{
        def name='sudhansu'
        def age=28
        def isEmployed=true
        def list=["Bangalore","Delhi","Bhubaneswar"]
        def map=[env_name:'prod']
    }
    stages{
        stage("groovy_variables")
        {
        
            steps{
                echo """Jenkins pipeline created by the author :${env.name} \n
                Age:${env.age} \n he is already employed:${env.isEmployed} \n           
                """
                script{
                    for (location in env.list){
                        echo "${name} is open to work in ${location}"
                    }
                echov "We are ready to deploy in ${env.map}"
                }
            }
        }
    }
}