@Library('jenkins-shared-lib@master') _    // 👈 Load shared library at the very top
import org.example.MathHelper       // 👈 Import class at the top.

pipeline {
    agent any
    stages {
        stage('Shared_library') {
            steps {
                echo 'Welcome to shared library steps'
                script {
                    def result = MathHelper.add(10, 20)
                    echo "libraries imported successfully without any error."
                    echo "10 + 20 = ${result}"
                }
            }
        }
        stage('deploy-app')
        {
            steps{
            greet('sudhansu')
            deployApp1('App1')
            deployApp2('App2')
            }
        }
        }
    }

