

pipeline
{
    agent any
    {
        stages
        {
            stage('Shared_library')
            {
                steps
                {
                    echo 'Welcome to shared library steps'
                    script
                    {
                        @Library('jenkins-shared-lib') _   // 👈 load the library by name
                        import org.example.MathHelper      // for src classes
                        echo "libraries imported successfully without any error."
                    }
                }
            }
        }
    }
}