pipeline {
    agent any

    environment {
        NAME = "Sudhansu"
        AGE = "28"
        IS_EMPLOYED = "true"
    }

    stages {
        Stage("STAGE-RECOVER USERNAME&PASSWORD")
        {
            steps
            {
                withCredentials([usernamePassword([
                    credentialsId:'sudhansu_personal',
                    usernameVariable:'USER',
                    passwordVariable:'PASS'
                ])])
                {
                    sh "User name:$USER"
                    sh "User password:$PASS"
                }
            }
        }
    }
}
