pipeline {
    agent any

    environment {
        NAME = "Sudhansu"
        AGE = "28"
        IS_EMPLOYED = "true"
    }

    stages {
        stage("STAGE-RECOVER USERNAME&PASSWORD")
        {
            steps
            {
                withCredentials([usernamePassword([
                    credentialsId:'sudhansu_personal',
                    usernameVariable:'USER',
                    passwordVariable:'PASS'
                ])])
                {
                    sh 'echo "User name:$USER"'
                    sh 'echo "User password:$PASS"'
                }
            }
        }
        stage("Executing multiple lines using sh/bat")
        {
            steps{
                script{
                    if (isUnix()){
                        sh """
                        echo  "executing multiple line using the linux command."
                        ls -l
                        """
                    }
                    else
                    {
                        bat """
                        echo  its a windows interface
                        dir
                        """
                    }
                }
            }
        }
        stage("Build a job")
        {
            steps{
                build job:"Trigger_job_pipeline",
                parameters:[booleanParam(name:'deployment_ready',value:true),
                string(name:'deployEnvironment',value:'test'),
                string(name:'authorName',value:'sudhansu')]   
            }
        }
    }
}
