pipeline {
    agent any

    environment {
        NAME = "Sudhansu"
        AGE = "28"
        IS_EMPLOYED = "true"
    }

    stages {
        stage('Stage-Credentials Fetch') {
            steps {
                echo "Started Credential stage..."
                script {
                    withCredentials([usernamePassword(
                        credentialsId: 'sudhansu_personal',
                        usernameVariable: 'USER',
                        passwordVariable: 'PASS'
                    )]) {
    sh 'echo "User name is $USER"'
    sh 'echo "Password is $PASS"'
                    }
                }
            }
        }
    }
}
