pipeline{
    agent any
    parameters{
        booleanParam(defaultValue:false,description:"Enable service",name:"myBoolean")
    }
    stages{
        stage("Demo")
        {
            steps{
                echo "boolean parameter is set to :${params.myBoolean}"
            }
        }
    }
}