pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Build Jenkins Job'
            }
        }
        stage('Test') {
            steps {
                echo 'Test Jenkins Job'
            }
        }
        stage('Deliver') { 
            steps {
                echo 'Deliver Jenkins Job'
            }
        }
    }
}
