pipeline{
    agent any
    environment{
        def secret_api=credentials('api-key')
    }
    stages{
        stage("Secret-keys")
        {
            steps
            {
                echo "API key for the app-access is :${env.secret_api}"
            }
        }
    }
}