pipeline{
    agent any
    environment{
        def secret_api=credentials('api-key')
    }
    stages{
        stage("Secret-keys")
        {
            steps
            {
                echo "API key for the app-access is :${env.secret_api}"  // Groovy
                // logging with bat command
                script
                {
                    if(!isUnix()){
                    bat """
                echo the secret key is with bat :%secret_api%   
                """
                }
                else{
                    // Logging with sh
                sh """
                echo 'secret key with sh:$secret_api'
                """
                }
                }
                
            }
        }
    }
}